language: node_js
node_js:
  - 10
addons:
  chrome: stable
  apt:
    packages:
      - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache
script:
  - cd example
  - npm install
  - npm start &
  - npm run e2e:audit:headless
  - kill $(jobs -p) || true
