language: node_js
node_js:
  - 14
addons:
  chrome: stable
  apt:
    packages:
      - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache

before_script:
  - npm i -g serve

script:
  - cd examples/cra-authenticated
  - yarn install
  - yarn build
  - serve -s build -l 3000 &
  - yarn e2e:audit:headless
  - kill $(jobs -p) || true

script:
  - cd examples/nextjs
  - yarn install
  - yarn build
  - yarn start &
  - yarn e2e:audit:headless
  - kill $(jobs -p) || true
