version: 2.1
jobs:
  e2e-nextjs:
    docker: 
      - image: cypress/browsers:node14.7.0-chrome84
    steps:
      - checkout
      - run: |
          cd examples/nextjs
          yarn install
          yarn build 
          yarn start &
          yarn e2e:audit:headless

workflows:
    version: 2.1
    build:
      jobs:
        - e2e-nextjs
   